# Generated by Django 5.0.2 on 2024-02-25 01:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('posted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
